---
- name: Ensure Spotify repository signing key is present
  become: yes
  when: ansible_os_family == "Debian"
  apt_key: keyserver=keyserver.ubuntu.com id=D2C19886

- name: Ensure Spotify repository is present
  become: yes
  when: ansible_os_family == "Debian"
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "deb http://repository.spotify.com stable non-free"
    #- "deb http://ftp.tw.debian.org/debian/ wheezy non-free main contrib"
    #- "deb http://security.debian.org/ wheezy/updates main"

#- name: Ensure libgcrypt11 in present
  #become: yes
  #when: ansible_os_family == "Debian"
  #apt: name=libgcrypt11 update_cache=yes cache_valid_time=3600 state=latest

- name: Ensure Spotify is the latest
  become: yes
  when: ansible_os_family == "Debian"
  apt: name=spotify-client update_cache=yes cache_valid_time=3600 state=latest

- name: Ensure Spotify is the latest
  become: yes
  when: ansible_os_family == "Darwin"
  homebrew_cask: name=spotify state=present
  ignore_errors: yes
