---
- name: Ensure Signal APT release key is present.
  become: yes
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Ensure Syncthing APT repository is present.
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal-xenial.list
    mode: 644
    state: present

- name: Ensure APT packages are the latest.
  become: yes
  apt:
    name:
      - firefox
      - calibre
      #- chromium
      - gnome-tweaks
      - signal-desktop
      - vlc
      #- fonts-opendyslexic
      #- wireshark
      #- xbacklight
      #- xclip
    state: latest
    update_cache: yes
