---
- name: ensure Spotify repository signing key is present
  when: ansible_system == "Linux"
  apt_key: keyserver=keyserver.ubuntu.com id=D2C19886

- name: ensure Spotify repository is present
  when: ansible_system == "Linux"
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "deb http://repository.spotify.com stable non-free"
    - "deb http://ftp.tw.debian.org/debian/ wheezy non-free main contrib"
    - "deb http://security.debian.org/ wheezy/updates main"

- name: ensure libgcrypt11 in present
  when: ansible_system == "Linux"
  apt: name=libgcrypt11 update_cache=yes cache_valid_time=3600 state=latest

- name: ensure Spotify is the latest
  when: ansible_system == "Linux"
  apt: name=spotify-client update_cache=yes cache_valid_time=3600 state=latest

- name: ensure Spotify is the latest
  when: ansible_system == "Darwin"
  homebrew_cask: name=spotify state=present
  ignore_errors: yes
