---
- name: Ensure hostname variable is defined.
  command: "false"
  when: not hostname

- name: Ensure hostname in /etc/hosts is set.
  become: yes
  lineinfile: 'regexp="^127\.0\.0\.1" dest=/etc/hosts create=yes state=present line="127.0.0.1\tlocalhost {{ hostname }}"'

- name: Ensure hostname is set.
  hostname: name={{ hostname }}

- name: Ensure APT packages are the latest.
  apt: name={{ item }} state=latest cache_valid_time=86400
  become: yes
  with_items:
    - ack-grep
    - aspell
    - autoconf
    - automake
    - bash-completion
    - calibre
    - chromium-browser
    - cmake
    - cscope
    - ctags
    - curl
    - dict
    #- dockertoolbox
    - espeak
    - ffmpeg
    - firefox
    - fortune
    - gist
    - git
    - git-annex
    - gnupg
    - graphicsmagick
    - graphviz
    #- hub
    - imagemagick
    - jpeginfo
    - jq
    - ledger
    - libreadline-dev
    - mcrypt
    - mercurial
    - mongodb
    - mosh
    - mr
    - msmtp
    - mutt
    - ncftp
    #- ngrok
    - nmap
    - offlineimap
    - openssl
    - pandoc
    - pdftohtml
    - pkg-config
    - pngquant
    - proj-bin
    - proj-data
    - pwgen
    - remind
    - rename
    - sqlite
    - tig
    - tmux
    - tree
    - unrar
    - vlc
    - w3m
    - webp
    - wget
    - wireshark
    - xclip
    #- hub

- name: Ensure APT 3rd party packages are the installed.
  apt: deb={{ item }} state=present
  become: yes
  with_items:
    - https://www.rescuetime.com/installers/rescuetime_current_amd64.deb
