---
- name: Install or update nvm to the latest version.
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm update=yes

- name: Ensure default Node.js version is the latest stable.
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install stable && nvm alias default stable

- name: Ensure global Node.js tools are the up-to-date.
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm exec stable npm install -g {{ item }}
  with_items:
    - pug-cli
    - stylus
    - babel-cli
    - eslint-cli
    - jscs
    - http-server
    - serve
    - live-server
    - localtunnel
    - standard
    - cloudflare-cli
    - statuscake-cli
    - geojsonio-cli
    - caniuse-cmd
    - moretext
