---
- name: Install nvm if it is not installed yet.
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm update=yes

- name: Ensure default Node.js version is the latest stable.
  shell: source $HOME/.nvm/nvm.sh && nvm install stable && nvm alias default stable

- name: Ensure global npm tools are the latest.
  npm: name={{ item }} executable="~/.nvm/nvm-exec npm" global=yes state=latest
  with_items:
    - jade
    - stylus
    - livescript
    - babel-cli
    - http-server
    - serve
    - live-server
    - localtunnel
    - standard
    - cloudflare-cli
    - statuscake-cli
    - geojsonio-cli
    - caniuse-cmd
    - moretext
