---
- name: Ensure nvm is the latest.
  become: no
  git: repo=https://github.com/creationix/nvm.git dest={{ ansible_env.HOME }}/.nvm clone=yes update=yes

- name: Ensure default Node.js is the latest {{ nodejs_version }}.
  become: no
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}
  args:
    executable: /bin/bash
