---
- name: Ensure nvm is the latest.
  become: no
  git: repo=https://github.com/creationix/nvm.git dest={{ ansible_env.HOME }}/.nvm clone=yes update=yes

- name: Ensure default Node.js is the latest stable.
  become: no
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install stable && nvm alias default stable
  args:
    executable: /bin/bash

- name: Ensure Node.js tools are the latest.
  become: no
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm exec stable npm install -g {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - pug-cli
    - stylus
    - babel-cli
    - eslint-cli
    - jscs
    - http-server
    - serve
    - live-server
    - localtunnel
    - standard
    - cloudflare-cli
    - statuscake-cli
    - geojsonio-cli
    - caniuse-cmd
    - moretext
