---
- name: Ensure nodebrew is present.
  become: no
  command: curl -L git.io/nodebrew | perl - setup
  args:
    creates: '{{ nodebrew_home }}'

- name: Ensure nodebrew is the latest.
  become: no
  command: nodebrew selfupdate
  environment:
    PATH: '{{ nodebrew_home }}/current/bin:{{ ansible_env.PATH }}'

- name: Ensure Node.js is present.
  become: no
  command: nodebrew install {{ nodebrew_nodejs_version }}
  environment:
    PATH: '{{ nodebrew_home }}/current/bin:{{ ansible_env.PATH }}'
  args:
    creates: '{{ nodebrew_home }}/node/*'

- name: Ensure Node.js is used.
  become: no
  command: nodebrew use {{ nodebrew_nodejs_version }}
  environment:
    PATH: '{{ nodebrew_home }}/current/bin:{{ ansible_env.PATH }}'
