---
- name: Ensure Perl toochain is the latest
  apt:
    name:
      - perl
      - cpanminus
      - carton
    state: latest
  become: yes

- name: Ensure Rakudo toolchain is the latest
  apt:
    name: rakudo-star
    state: latest
  become: yes
