---
- name: Ensure Perl toochain is the latest
  apt:
    name:
      - perl
      - cpanminus
      - carton
      - liblocal-lib-perl
    state: latest
  become: yes

- name: Ensure Rakudo toolchain is the latest
  apt:
    name: rakudo
    state: latest
  become: yes

- name: Ensure OPAM is the latest
  apt:
    name: opam
    state: latest
  become: yes
