---
- name: ensure pyenv is the latest
  git: repo=https://github.com/yyuu/pyenv.git clone=yes dest=~/.pyenv update=yes

- name: ensure Python packages are the latest
  pip: name={{ item }} state=present
  with_items:
    - autopep8
    - ipython
