---
- include: setup-{{ ansible_os_family }}.yml

- name: Ensure pyenv is the latest.
  git: repo=https://github.com/yyuu/pyenv.git clone=yes dest=~/.pyenv update=yes

- name: Ensure Python versions are present.
  shell: pyenv install {{ item }}
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: '{{ python_versions }}'

- name: Ensure global Python version is present.
  shell: pyenv global {{ python_global_version }}

- name: Ensure Python packages are the latest.
  pip: name={{ item }} state=present
  with_items:
    - autopep8
    - ipython
    - pytest
    - virtualenv
