---
- name: Ensure build dependencies are the latest
  yum: name={{ item }} state=latest
  with_items:
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
