---
- name: Ensure build dependencies are the latest
  become: yes
  apt: name={{ item }} state=latest cache_valid_time=86400
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
