---
- name: Ensure hostname var is defined
  command: 'false'
  when: not hostname

- name: Ensure hostname is {{hostname}}
  become: yes
  shell: scutil --set HostName {{hostname}}

- name: Ensure localhostname is {{hostname}}
  become: yes
  shell: scutil --set LocalHostName {{hostname}}

- name: Ensure computer name is {{hostname}}
  become: yes
  shell: scutil --set ComputerName {{hostname}}

- name: Ensure Homebrew is tapped to homebrew/cask
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: Ensure Homebrew itself and installed packages are the latest
  homebrew:
    state: latest
    update_homebrew: yes
    upgrade_all: yes

- name: Ensure Homebrew packages are the latest
  ignore_errors: yes
  homebrew:
    state: latest
    name:
      - aspell
      - autoconf
      - automake
      - bash-completion
      - bvi
      - cmake
      - cowsay
      - cscope
      - ctags
      - curl
      - dict
      - espeak
      - ffmpeg
      - fortune
      - git
      - git-annex
      - gnupg
      - graphicsmagick
      - graphviz
      - imagemagick
      - java
      - jpeg
      - jq
      - mcrypt
      - mhash
      - mobile-shell
      - mr
      - msmtp
      - mutt
      - ncftp
      - nmap
      - openssl
      - pandoc
      - pkg-config
      - pwgen
      - readline
      - rename
      - sl
      - sqlite
      - tig
      - tmux
      - tree
      - unrar
      - w3m
      - webp
      - wget

- name: Ensure Homebrew Cask packages are the latest
  homebrew_cask: name={{ item }} state=present
  ignore_errors: yes
  with_items:
    - amethyst
    - coconutbattery
    - firefoxdeveloperedition
    - chromium
    - gpg-suite
    - iterm2
    - min
    - the-unarchiver
    - typora
    - vlc
    - wireshark
