---
- name: Ensure hostname variable is defined.
  command: "false"
  when: not hostname

- name: Ensure hostname in /etc/hosts is set.
  become: yes
  lineinfile: 'regexp="^127\.0\.0\.1" dest=/etc/hosts create=yes state=present line="127.0.0.1\tlocalhost {{ hostname }}"'

- name: Ensure hostname is set.
  become: yes
  hostname: name={{ hostname }}

- name: Ensure APT packages are the latest.
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=86400
  become: yes
  with_items:
    - ack
    - acpi
    - aptitude
    - aspell
    - autoconf
    - automake
    - bash-completion
    - bzr
    #- calibre
    #- chromium
    - cmake
    - cscope
    - ctags
    - curl
    - dict
    #- dockertoolbox
    - debfoster
    - espeak
    - ffmpeg
    #- iceweasel
    - fortune
    #- fonts-opendyslexic
    - gist
    - git
    - git-annex
    - git-lfs
    - gnupg
    - graphicsmagick
    - graphviz
    #- hub
    - imagemagick
    - jpeginfo
    - jq
    - ledger
    - libreadline-dev
    - mcrypt
    - mercurial
    - mosh
    - mr
    - msmtp
    - mutt
    - ncftp
    #- ngrok
    - nmap
    - offlineimap
    - openssl
    - pandoc
    - pdftohtml
    - pkg-config
    - pngquant
    - proj-bin
    - proj-data
    #- vlc
    - w3m
    - webp
    - wget
    #- wireshark
    #- xbacklight
    #- xclip
    - whois

- name: Ensure Deiabn system is upgraded.
  become: yes
  apt: update_cache=yes upgrade=yes cache_valid_time=86400

- name: Ensure APT 3rd party packages are the installed.
  apt: deb={{ item }} state=present
  become: yes
  with_items:
    - https://www.rescuetime.com/installers/rescuetime_current_amd64.deb

- name: Telegram - check
  file: dest=~/bin/telegram state=file
  ignore_errors: yes
  register: telegram

- name: Telegram - download
  get_url: url=https://telegram.org/dl/desktop/linux dest=~/tmp/Telegram.tar.xz
  when: telegram|failed

- name: Telegram - extract
  unarchive: dest=~/tmp src=~/tmp/Telegram.tar.xz copy=no
  when: telegram|failed

- name: Telegram - copy
  command: cp ~/tmp/Telegram/Telegram ~/bin/telegram
  when: telegram|failed
