---
- name: Ensure hostname variable is defined.
  command: "false"
  when: not hostname

- name: Ensure hostname in /etc/hosts is set.
  become: yes
  lineinfile: 'regexp="^127\.0\.0\.1" dest=/etc/hosts create=yes state=present line="127.0.0.1\tlocalhost {{ hostname }}"'

- name: Ensure hostname is set.
  become: yes
  hostname: name={{ hostname }}
  when: ansible_os_family != "Pop!_OS"

- name: Ensure APT packages are the latest.
  apt:
    name:
      - ack
      - acpi
      - aptitude
      - aspell
      - autoconf
      - automake
      - bash-completion
      - bzr
      #- calibre
      #- chromium
      - cmake
      - cscope
      - universal-ctags
      - curl
      - dict
      #- dockertoolbox
      - debfoster
      - espeak
      - ffmpeg
      #- iceweasel
      - fortune
      #- fonts-opendyslexic
      - gist
      - git
      - git-annex
      - git-lfs
      - gnupg
      - graphicsmagick
      - graphviz
      #- hub
      - imagemagick
      - jpeginfo
      - jq
      - ledger
      - libreadline-dev
      - mcrypt
      - mercurial
      - mosh
      - mr
      - msmtp
      - mutt
      - ncftp
      #- ngrok
      - nmap
      - offlineimap
      - openssl
      - pandoc
      - pdftohtml
      - pkg-config
      - pngquant
      - proj-bin
      - proj-data
      - rename
      - tmux
      #- vlc
      - w3m
      - webp
      - wget
      #- wireshark
      #- xbacklight
      #- xclip
      - whois
      - vim-nox
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Ensure Debian system is upgraded.
  become: yes
  apt: update_cache=yes upgrade=yes cache_valid_time=86400
