---
- name: Ensure hostname variable is defined.
  command: "false"
  when: not hostname

- name: Ensure hostname in /etc/hosts is set.
  become: yes
  lineinfile: 'regexp="^127\.0\.0\.1" dest=/etc/hosts create=yes state=present line="127.0.0.1\tlocalhost {{ hostname }}"'

- name: Ensure hostname is set.
  become: yes
  hostname: name={{ hostname }}

- name: Ensure APT packages are the latest.
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=86400
  become: yes
  with_items:
    - ack
    - acpi
    - aptitude
    - aspell
    - autoconf
    - automake
    - bash-completion
    - bzr
    #- calibre
    #- chromium
    - cmake
    - cscope
    - ctags
    - curl
    - dict
    #- dockertoolbox
    - debfoster
    - espeak
    - ffmpeg
    #- iceweasel
    - fortune
    #- fonts-opendyslexic
    - gist
    - git
    - git-annex
    - git-lfs
    - gnupg
    - graphicsmagick
    - graphviz
    #- hub
    - imagemagick
    - jpeginfo
    - jq
    - ledger
    - libreadline-dev
    - mcrypt
    - mercurial
    - mosh
    - mr
    - msmtp
    - mutt
    - ncftp
    #- ngrok
    - nmap
    - offlineimap
    - openssl
    - pandoc
    - pdftohtml
    - pkg-config
    - pngquant
    - proj-bin
    - proj-data
    - rename
    #- vlc
    - w3m
    - webp
    - wget
    #- wireshark
    #- xbacklight
    #- xclip
    - whois

- name: Ensure Debian system is upgraded.
  become: yes
  apt: update_cache=yes upgrade=yes cache_valid_time=86400

- name: Ensure system default Python is set to Python 3.
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python2
    priority: 40

- name: Ensure system default Python is set to Python 3.
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: Ensure system default Pip is set to Pip 3.
  become: yes
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: Ensure system default PyDoc is set to PyDoc 3.
  become: yes
  alternatives:
    name: pydoc
    link: /usr/bin/pydoc
    path: /usr/bin/pydoc2
    priority: 40

- name: Ensure system default PyDoc is set to PyDoc 3.
  become: yes
  alternatives:
    name: pydoc
    link: /usr/bin/pydoc
    path: /usr/bin/pydoc3

- name: Ensure system default Python virtualenv is the latest.
  become: yes
  apt:
    name: python3-venv
    state: latest
