---
- name: Ensure PHPBrew is present.
  get_url: dest=~/bin/phpbrew url=https://github.com/phpbrew/phpbrew/raw/master/phpbrew mode=0755
  register: phpbrew

- name: Ensure PHPBrew is initialized.
  shell: phpbrew init creates=~/.phpbrew/init

- name: Ensure PHPBrew is updated.
  shell: phpbrew self-update

- name: Ensure PHPBrew known versions are updated.
  shell: phpbrew update

- name: Check the latest known PHP version
  shell: phpbrew known | head -n 1 | awk '{print $2}' | sed 's/,//g'
  register: phpbrew_php_version

- name: Ensure build environment is set.
  include: setup-Darwin.yml
  when: ansible_os_family == "Darwin"

- name: Ensure PHP {{ phpbrew_php_version.stdout }} is the present.
  shell: phpbrew install {{ phpbrew_php_version.stdout }} +default +fpm -- --with-openssl=/usr/local --without-bz2
  args:
    creates: ~/.phpbrew/php/php-{{ phpbrew_php_version.stdout }}

- name: Ensure PHP {{ phpbrew_php_version.stdout }} is the default.
  shell: source ~/.phpbrew/bashrc && phpbrew switch $(phpbrew list | grep php | head -n 1)

- name: Ensure Composer is present.
  shell: (curl -sS https://getcomposer.org/installer | php) && mv composer.phar $HOME/bin
  args:
    creates: ~/bin/composer.phar

- name: Ensure Composer is updated.
  shell: composer.phar self-update.
