---
- name: ensure PHPBrew is present
  get_url: dest=~/bin/phpbrew url=https://github.com/phpbrew/phpbrew/raw/master/phpbrew mode=0755
  register: phpbrew

- name: ensure PHPBrew is the latest
  shell: phpbrew self-update

- name: ensure PHPBrew environment is initialized
  shell: phpbrew init creates=~/.phpbrew/init
  ignore_errors: yes

- name: ensure Homebrew Dupes is tapped
  when: ansible_os_family == "Darwin"
  homebrew_tap: tap=homebrew/dupes state=present

- name: ensure Homebrew dependencies are the latest
  when: ansible_os_family == "Darwin"
  homebrew: name={{ item }} state=latest
  with_items:
    - openssl
    - curl
    - readline
    - zlib

# openssl
- name: ensure Homebrew dependencies are linked
  when: ansible_os_family == "Darwin"
  shell: brew link {{ item }} --force
  #homebrew: name={{ item }} state=linked install_options=--force
  with_items:
    - openssl
    - curl
    - readline
    - zlib

- name: ensure PHP {{ phpbrew_php_version }} is the latest
  shell: phpbrew install {{ phpbrew_php_version }} +default +fpm -- --with-openssl=/usr/local --without-bz2
  args:
    creates: ~/.phpbrew/php/php-{{ phpbrew_php_version }}

- name: ensure PHP {{ phpbrew_php_version }} is used by default
  shell: source ~/.phpbrew/bashrc && phpbrew switch $(phpbrew list | grep php | head -n 1)

- name: ensure composer is the latest
  shell: source ~/.phpbrew/bashrc && phpbrew install-composer

- name: ensure phpunit is the latest
  shell: source ~/.phpbrew/bashrc && phpbrew install-phpunit
