---
- include: setup-{{ ansible_system }}.yml

- name: Ensure fzf is the latest
  git: repo=https://github.com/junegunn/fzf.git clone=yes dest={{ ansible_env.HOME }}/.fzf depth=1

- name: Ensure fzf is installed
  command: "{{ ansible_env.HOME }}/.fzf/install chdir={{ ansible_env.HOME }} creates={{ ansible_env.HOME }}/.fzf.bash"
