---
- hosts: localhost
  vars:
    phpbrew_php_version: 7.0.7
  roles:
    - darwin
    - vim
    - syncthing
    - nodejs
    - python
    - ruby
    - php
    - haskell
    - golang
    - blender
    - photo
    - gis
    - datasci
    - machinelearning
