---
- name: Ensure Syncthing APT release key is present.
  become: yes
  apt_key:
    url: https://syncthing.net/release-key.txt

- name: Ensure Syncthing APT repository is present.
  become: yes
  apt_repository:
    repo: deb http://apt.syncthing.net/ syncthing release
    mode: 644

- name: Ensure Syncthing APT package is the latest.
  become: yes
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    name:
      - syncthing
