---
- name: Ensure Syncthing Homebrew package is the latest.
  homebrew:
    name: syncthing
    state: latest
  ignore_errors: yes

- name: Ensure Syncthing launchd configuration is present.
  command: brew services start syncthing
