---
- name: Ensure RVM gnupg key is present.
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Ensure RVM is the latest stable.
  shell: curl -sSL https://get.rvm.io | bash -s latest

- name: Ensure RVM is the latest stable.
  shell: export PATH=$HOME/.rvm/bin:$PATH && source $HOME/.rvm/scripts/rvm && rvm get latest

- name: Ensure all Ruby versions are present.
  shell: export PATH=$HOME/.rvm/bin:$PATH && source $HOME/.rvm/scripts/rvm && rvm install {{ item }}
  args:
    executable: /bin/bash
  with_items: '{{ ruby_versions }}'

- name: Ensure default Ruby version is {{ ruby_default_version }}.
  shell: export PATH=$HOME/.rvm/bin:$PATH && source $HOME/.rvm/scripts/rvm && rvm default {{ ruby_default_version }}@global
  args:
    executable: /bin/bash

- name: Ensure Ruby gems are the latest.
  gem: name={{ item }} state=latest
  with_items:
    - moretext
    - terminal-notifier
    - t
